<div class="content-area">

	<h1>TERMS &amp; CONDITIONS</h1>	
	<hr>
	<p>By clicking “sign in”, “create account” or “submit order” and entering or otherwise using our website or mobile application (the “Site”), you agree to and accept these terms and conditions. Certain products and services on our Site may have additional terms that apply (for example, if you subscribe to our Autoship &amp; Save subscription program, you also will be subject to the Autoship Terms &amp; Conditions). If these Terms of Use are inconsistent with terms applicable to a certain product or service, those other terms will control.</p>
		<p>THESE TERMS AND CONDITIONS, AS WELL AS ANY OTHER PRODUCT AND SERVICE SPECIFIC TERMS ON OUR SITE, CONSTITUTE YOUR SERVICE AGREEMENT (“AGREEMENT”) WITH PETSSIFIED.COM AND ANY OF ITS OWNED OR OPERATED SITES WHERE THESE TERMS OF UES ARE POSTED (“PETSSIFIED.COM “). THIS AGREEMENT SETS FORTH THE LEGALLY BINDING TERMS FOR YOUR USE OF OUR SITE AND YOUR PURCHASE OR USE OF ANY PRODUCTS OR SERVICES OFFERED ON THE SITE. BY ACCESSING AND/OR USING THE SITE, YOU REPRESENT AND WARRANT THAT YOU HAVE THE RIGHT, AUTHORITY, AND CAPACITY TO ENTER INTO THE AGREEMENT AND TO ABIDE BY ALL OF THE TERMS AND CONDITIONS SET FORTH HEREIN. YOU MAY NOT ACCESS OR USE THIS SITE OR ACCEPT THIS AGREEMENT UNLESS YOU ARE AT LEAST 18 YEARS OLD.
			<br>ARBITRATION NOTICE: THESE TERMS CONTAIN AN ARBITRATION CLAUSE A LITTLE LATER ON. YOU AND PETSSIFIED.COM AGREE THAT DISPUTES BETWEEN US WILL BE RESOLVED BY MANDATORY BINDING ARBITRATION, AND YOU AND PETSSIFIED.COM WAIVE ANY RIGHT TO PARTICIPATE IN A CLASS-ACTION LAWSUIT OR CLASS-WIDE ARBITRATION.</p>
		<p><strong>Privacy Policy</strong>
			<br>Please review our Privacy Policy, which also governs your use of our Site, to understand our practices.</p>
		<p><strong>Electronic Communications</strong>
			<br>When you use our Site, or send e-mails, text messages, and other communications from your desktop or mobile device to us, you are communicating with us electronically. You consent to receive communications from us electronically, such as e-mails, texts, mobile push notices, or notices and messages on this Site, and you can retain copies of these communications for your records. You agree that all agreements, notices, disclosures, and other communications that we provide to you electronically satisfy any legal requirement that such communications be in writing.</p>
		<p><strong>Accounts</strong>
			<br>In order to use certain features of the Site (e.g., purchasing products and services (referred to collectively as “Products” herein) from the Site), you must register for an account with&nbsp;<strong>PETSSIFIED.COM</strong>&nbsp;(“<strong>PETSSIFIED.COM Account</strong>“) and provide certain information about yourself as prompted by the Site registration form. You represent and warrant that: (a) all required registration information you submit is truthful and accurate; (b) you will maintain the accuracy of such information; and (c) your use of the Site does not violate any applicable law or regulation or the terms of this Agreement.
			<br>You are responsible for maintaining the confidentiality of your&nbsp;<strong>PETSSIFIED.COM</strong>&nbsp;Account login information. You are fully responsible for all activities that are associated with your&nbsp;<strong>PETSSIFIED.COM</strong>&nbsp;Account (including but not limited to any purchases, use of the Site, or correspondence from your account to&nbsp;<strong>PETSSIFIED.COM</strong>&nbsp;). You agree to immediately notify&nbsp;<strong>PETSSIFIED.COM</strong>&nbsp;of any unauthorized use or suspected unauthorized use of your&nbsp;<strong>PETSSIFIED.COM</strong>&nbsp;Account or any other breach of security. When you provide&nbsp;<strong>PETSSIFIED.COM</strong>&nbsp;with such notice,&nbsp;<strong>PETSSIFIED.COM</strong>&nbsp;will suspend or otherwise secure your Account to prevent future unauthorized activity.</p>
		<p><strong>Order Acceptance</strong>
			<br>The receipt of an order number or an email order confirmation does not constitute the acceptance of an order or a confirmation of an offer to sell. PETSSIFIED.COM reserves the right, without prior notification, to limit the order quantity on any item and/or to refuse service to any customer. Verification of information may be required prior to the acceptance of an order. Prices and availability of products on the Site are subject to change without notice. Errors will be corrected when discovered and&nbsp;<strong>PETSSIFIED.COM</strong>&nbsp;reserves the right to revoke any stated offer and to correct any error, inaccuracy, or omission (including after an order has been submitted). Certain orders constitute improper use of the Site.&nbsp;<strong>PETSSIFIED.COM</strong>reserves the right, at its sole discretion, to refuse or cancel any order for any reason. Your account may also be restricted or terminated for any reason, at&nbsp;<strong>PETSSIFIED.COM</strong>&nbsp;‘s sole discretion.</p>
		<p><strong>Risk of Loss</strong>
			<br>All items purchased from&nbsp;<strong>PETSSIFIED.COM</strong>&nbsp;are made pursuant to a shipment contract. This means that the risk of loss and title for such items pass to you upon our delivery to the carrier.</p>
		<p><strong>Product Descriptions</strong>
			<br><strong>PETSSIFIED.COM</strong>&nbsp;attempts to be as accurate as possible. However,&nbsp;<strong>PETSSIFIED.COM</strong>&nbsp;does not warrant that product descriptions or other content on the Site are accurate, complete, reliable, current or error-free. If a product offered by&nbsp;<strong>PETSSIFIED.COM</strong>&nbsp;is not as described, your sole remedy is to return the product.</p>
		<p><strong>Pricing</strong>
			<br>“<strong>List Price</strong>” means the suggested retail price of a product as provided by a manufacturer, supplier or other retailers (and with respect to RX products, veterinarians). Certain products may have a “RETAIL Price” displayed, which is determined using recent price history of the product on PETSSIFIED.COM .com.
			<br>PETSSIFIED.COM cannot confirm the price of an item until your submit an order. If you use Autoship, the price of an item will set at the time the order is processed. See Autoship Terms and Conditions for more information. Despite our best efforts, a small number of the items in our catalog may be mispriced. If the correct price of an items is higher than our stated price, we will, at our discretion, either contact you for instructions before shipping or cancel our order and notify you of such cancellation. We do business throughout the United States and collect and remit sales tax as required by law.</p>
		<p>By checking “Yes, make my life easy” on the&nbsp;<strong>PETSSIFIED.COM</strong>&nbsp;checkout page, you agree to the Autoship &amp; Save Terms and Conditions(“Autoship Terms”) applicable to our subscription ordering program (“Autoship”). The Autoship Terms govern your Autoship subscription, in addition to the Terms of Use and Privacy Policy that govern the use of our website, as well as all other applicable terms, conditions, limitations and requirements on the&nbsp;<strong>PETSSIFIED.COM</strong>&nbsp;.com website (as changed over time). By placing an order and enrolling in our Autoship program, you accept these terms, conditions, limitations and requirements. Please read these Terms carefully.</p>
		<p><strong>Permissible Uses of Site</strong></p>
		<p>Subject to the terms of this Agreement,&nbsp;<strong>PETSSIFIED.COM</strong>&nbsp;grants you a limited, non-transferable, non-exclusive, license to access and make personal use of the Site. This license does not include any resale or commercial use of the Site features or content, or the right to access or use the Site for any of the restricted purposes set forth below.&nbsp;<strong>PETSSIFIED.COM</strong>&nbsp;may terminate this license at any time for any reason.</p>
		<p>The rights granted to you in this Agreement are subject to the following restrictions: (a) you shall not use the Site to place an order on behalf of yourself or a third party for resale to that third party; (b) you shall not license, sublicense, reproduce, sell, rent, lease, transfer, assign, distribute, host, or otherwise commercially exploit the Site, its products or its content without the express written consent of&nbsp;<strong>PETSSIFIED.COM</strong>&nbsp;; (b) you shall not modify, make derivative works of, disassemble, reverse compile or reverse engineer any part of the Site; (c) you shall not access the Site in order to build a similar or competitive service, or to download, copy or collect content or account information for the benefit of another merchant; (d) except as expressly stated herein, no part of the Site may be copied, reproduced, distributed, republished, downloaded, displayed, posted or transmitted in any form or by any means without&nbsp;<strong>PETSSIFIED.COM</strong>&nbsp;‘s express written consent; and (e) you shall not frame or utilize framing techniques to enclose any trademark, logo, or other proprietary information or content (including images and text descriptions) of the Site without&nbsp;<strong>PETSSIFIED.COM</strong>&nbsp;‘s express written consent.
			<br><strong>PETSSIFIED.COM</strong>&nbsp;reserves the right, at any time, to modify, suspend, or discontinue the Site or any part thereof with or without notice. You agree that&nbsp;<strong>PETSSIFIED.COM</strong>&nbsp;will not be liable to you or to any third party for any modification, suspension, or discontinuance of the Site or any part thereof.</p>
		<p><strong>Intellectual Property Rights</strong></p>
		<p>The Site contains valuable trademarks and service marks owned and used by&nbsp;<strong>PETSSIFIED.COM</strong>&nbsp;luding but not limited to, PETSSIFIED.COM , the&nbsp;<strong>PETSSIFIED.COM</strong>&nbsp;design logo, the tag line “where pet lover shop” and certain brands including Tylee’s, Dr. Lyons, Frisco and American Journey (collectively, the “<strong>PETSSIFIED.COM</strong>&nbsp;Marks”). Any use of the&nbsp;<strong>PETSSIFIED.COM</strong>&nbsp;Marks without the prior written permission of&nbsp;<strong>PETSSIFIED.COM</strong>&nbsp;is strictly prohibited. The arrangement and layout of the Site, including but not limited to, the&nbsp;<strong>PETSSIFIED.COM</strong>&nbsp;Marks, images, text, graphics, buttons, screenshots, and other content or material (collectively, the “Site Content”), are the sole and exclusive property of&nbsp;<strong>PETSSIFIED.COM</strong>.</p>
		<p><strong>UNAUTHORIZED COPYING, REPRODUCTION, MODIFYING, REPUBLISHING, UPLOADING, DOWNLOADING, POSTING, TRANSMITTING, MAKING DERIVATIVE WORKS OF OR DUPLICATING ALL OR ANY PART OF THE SITE IS PROHIBITED.</strong></p>
		<p><strong>PETSSIFIED.COM</strong>&nbsp;uses a network of independent product and content suppliers, distributors and other such third parties to supply some of the products and content advertised on the Site. All other trademarks, service marks, product names, package designs and company names or logos associated with these product and other such third parties that are not owned by us but appear on the Site are the property of their respective owners.</p>
		<p><strong>Limitations Regarding Information, Articles and Advice</strong>
			<br><strong>PETSSIFIED.COM</strong>&nbsp;offers information, articles and advice to pet parents through this site for educational purposes only. Any information offered through this site is not intended to diagnose, treat or cure your pet and is not a substitute for veterinary care provided by a licensed veterinarian. For any medical or health related advice concerning the care and treatment of your pet contact your regulator veterinarian or local animal hospital.</p>
		<p><strong>User Content</strong>
			<br>“User Content” of the Site user means any and all information and content that such user submits to&nbsp;<strong>PETSSIFIED.COM</strong>&nbsp;by any means, including through social media (e.g., Facebook, YouTube, Instagram, Pinterest, Twitter), or uses with the Site (e.g., a user profile, product review, question &amp; answer). You are solely responsible for your User Content. You assume all risks associated with use of your User Content, including any reliance on its accuracy, completeness or usefulness by others, or any disclosure of your User Content that makes you or any third party personally identifiable. You hereby affirm, represent, and warrant that (i) you own, or have the necessary licenses, rights, and/or consents to use your User Content with the Site as described herein and (ii) your User Content does not violate the Acceptable Use Policy. You may not state or imply that your User Content is in any way provided, sponsored or endorsed by&nbsp;<strong>PETSSIFIED.COM</strong>&nbsp;. Because you alone are responsible for your User Content (and not&nbsp;<strong>PETSSIFIED.COM</strong>&nbsp;), you may expose yourself to liability if, for example, your User Content violates the Acceptable Use Policy.&nbsp;<strong>PETSSIFIED.COM</strong>&nbsp;is not obligated to backup any User Content, makes no representation that it will do so, and you agree that&nbsp;<strong>PETSSIFIED.COM</strong>&nbsp;may delete User Content at any time.</p>
		<p>By submitting your User Content or using it with the Site , you automatically grant, and you represent and warrant that you have the right to grant, to&nbsp;<strong>PETSSIFIED.COM</strong>&nbsp;an irrevocable, nonexclusive, royalty-free and fully paid, worldwide license to reproduce, distribute, publicly display and perform, prepare derivative works of, incorporate into other works, and otherwise use your User Content, and to grant sublicenses of the foregoing, solely for the purposes of including your User Content in the Site,&nbsp;<strong>PETSSIFIED.COM</strong>&nbsp;social media platforms or marketing initiatives. You agree to irrevocably waive (and cause to be waived) any claims and assertions of publicity or moral rights, or attribution with respect to your User Content.</p>
		<p><strong>PETSSIFIED.COM</strong>&nbsp;will treat any feedback, communications, or suggestions you provide to&nbsp;<strong>PETSSIFIED.COM</strong>&nbsp;as non-confidential and non-proprietary. Thus, in the absence of a written agreement with&nbsp;<strong>PETSSIFIED.COM</strong>&nbsp;to the contrary, you agree that you will not submit to&nbsp;<strong>PETSSIFIED.COM</strong>&nbsp;any information or ideas that you consider to be confidential or proprietary.</p>
		<p><strong>Acceptable Use Policy</strong>
			<br>You agree not to use the Site to collect, upload, transmit, display, or distribute any User Content (a) that violates any third-party right, including any copyright, trademark, patent, trade secret, moral right, privacy right, right of publicity, or any other intellectual property or proprietary right; (b) that is unlawful, harassing, abusive, tortious, threatening, harmful, abusive, invasive of another’s privacy, vulgar, defamatory, false, intentionally misleading, trade libelous, pornographic, obscene, patently offensive (e.g., material that promotes racism, bigotry, hatred, or physical harm of any kind against any group or individual) or otherwise objectionable material of any kind or nature or which is harmful to minors in any way; or (c) in violation of any law, regulation, or obligations or restrictions imposed by any third party.</p>
		<p>In addition, you agree not to commercially exploit the Site or use it to: (a) upload, transmit, or distribute any computer viruses, worms, or any software intended to damage or alter a computer system or data; (b) send unsolicited or unauthorized advertising, promotional materials, junk mail, spam, chain letters, pyramid schemes, or any other form of duplicative or unsolicited messages, whether commercial or otherwise; (c) harvest, collect, gather or assemble information or data regarding other users, including e-mail addresses, without their consent; (d) interfere with or disrupt servers or networks connected to the Site or violate the regulations, policies or procedures of such networks; (e) attempt to gain unauthorized access to the Site, other computer systems or networks connected to or used together with the Site, through password mining or other means; or (f) harass or interfere with another user’s use and enjoyment of the Site.</p>
		<p>We reserve the right (but have no obligation under this Agreement) to review any User Content, investigate, and/or take appropriate action against you, at our sole discretion, if you violate the Acceptable Use Policy or any other provision of this Agreement, including removing or modifying your User Content, terminating your&nbsp;<strong>PETSSIFIED.COM</strong>&nbsp;Account, and/or reporting you to law enforcement authorities. We may also remove or modify your User Content if it, in our sole judgment, violates the rights of, harms, or threatens the safety of any other person, or creates liability for us or any other person. In order to cooperate with legitimate governmental requests, subpoenas or court orders, or to protect our business and members, we may access and disclose any information we consider necessary or appropriate, including your&nbsp;<strong>PETSSIFIED.COM</strong>&nbsp;Account username and password, IP address and traffic information, usage history, and your User Content.</p>
		<p><strong>Third Party Sites and Other Users</strong>
			<br>The Site may contain links to, or advertisements for, third party web sites (collectively, “Third Party Sites”) (for example, social media sites such as Facebook, YouTube, Twitter, or Pinterest). Such Third Party Sites are not under the control of&nbsp;<strong>PETSSIFIED.COM</strong>&nbsp;and&nbsp;<strong>PETSSIFIED.COM</strong>&nbsp;is not responsible for any Third Party Sites.&nbsp;<strong>PETSSIFIED.COM</strong>&nbsp;provides links to these Third Party Sites only as a convenience and does not review, approve, monitor, endorse, warrant, or make any representations with respect to Third Party Sites. You agree that you use all Third Party Sites at your own risk. When you link to a Third Party Site, the applicable service provider’s terms and policies, including privacy and data gathering practices govern. You should make whatever investigation you feel necessary or appropriate before proceeding with any transaction with any Third Party Site.
			<br>Each Site user is solely responsible for any and all of its User Content. Because we do not control User Content, you acknowledge and agree that we are not responsible for any User Content and we make no guarantees regarding the accuracy, currency, suitability, or quality of any User Content, and we assume no responsibility for any User Content. Your interactions with other Site users are solely between you and such user. You agree that&nbsp;<strong>PETSSIFIED.COM</strong>&nbsp;will not be responsible for any loss or damage incurred as the result of any such interactions. If there is a dispute between you and any Site user, we are under no obligation to become involved.</p>
		<p>You hereby release us, our officers, employees, agents, affiliates, subsidiaries, parents, joint ventures, successors and any other companies under common control with us from claims, demands any and all losses, damages, rights, claims, and actions of any kind including personal injuries, death, and property damage, that are either directly or indirectly related to or arise out of any interactions with or conduct of other Site users or Third Party Sites.</p>
		<p><strong>Disclaimer of Warranties</strong>
			<br><strong>PETSSIFIED.COM</strong>&nbsp;intends for the information and data contained in the Site to be accurate and reliable but since the information and data have been compiled from a variety of sources, they are provided ‘AS IS’ and “AS AVAILABLE”. You expressly agree that your use of the Site and any information contained therein is at your sole risk. NEITHER&nbsp;<strong>PETSSIFIED.COM</strong>&nbsp;NOR ITS THIRD PARTIES WARRANT THE ACCURACY, OR COMPLETENESS OF THE CONTENT PROVIDED ON THIS SITE OR THE PRODUCTS OR SERVICES OFFERED FOR SALE ON THIS SITE. WE CANNOT AND DO NOT WARRANT THAT YOUR USE OF THIS SITE WILL BE UNINTERRUPTED, SECURE OR ERROR FREE. Accordingly, to the extent permitted by applicable law,&nbsp;<strong>PETSSIFIED.COM</strong>&nbsp;EXPRESSLY DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION, IMPLIED WARRANTIES OF TITLE, NON-INFRINGEMENT, ACCURACY, MERCHANTABILITY AND FITNESS FOR A PURPOSE, AND ANY WARRANTIES THAT MAY ARISE FROM COURSE OF DEALING, COURSE OF PERFORMANCE OR USAGE OF TRADE. Some jurisdictions do not allow the disclaimer of warranties so such disclaimers may not apply to you.</p>
		<p><strong>Limitation on Liability</strong>
			<br>IN NO EVENT SHALL&nbsp;<strong>PETSSIFIED.COM&nbsp;, OUR OFFICERS, EMPLOYEES, AGENTS, AFFILIATES, SUBSIDIARIES, PARENTS, JOINT VENTURES, SUCCESSORS AND ANY OTHER COMPANIES UNDER COMMON CONTROL WITH US BE LIABLE TO YOU OR ANY THIRD PARTY FOR ANY LOST PROFIT OR ANY INDIRECT, CONSEQUENTIAL, EXEMPLARY, INCIDENTAL, SPECIAL OR PUNITIVE DAMAGES ARISING FROM OR IN ANY WAY RELATED TO YOUR RELATIONSHIP WITHPETSSIFIED.COM&nbsp;, YOUR USE OF THE WEB SITE, PRODUCTS, OR THIRD PARTY SITES, EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. ACCESS TO, AND USE OF, THE WEB SITE, PRODUCTS AND THIRD PARTY SITES ARE AT YOUR OWN DISCRETION AND RISK, AND YOU WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOUR COMPUTER SYSTEM OR LOSS OF DATA RESULTING THEREFROM. NOTWITHSTANDING ANYTHING TO THE CONTRARY CONTAINED HEREIN, OUR LIABILITY TO YOU FOR ANY DAMAGES ARISING FROM OR IN ANY WAY RELATED TO YOUR RELATIONSHIP WITH&nbsp;PETSSIFIED.COM&nbsp;OR THIS AGREEMENT (FOR ANY CAUSE WHATSOEVER AND REGARDLESS OF THE FORM OF THE ACTION), WILL AT ALL TIMES BE LIMITED TO THE GREATER OF (A) FIFTY US DOLLARS ($50) OR (B) AMOUNTS YOU’VE PAID&nbsp;PETSSIFIED.COM&nbsp;IN THE PRIOR 12 MONTHS. WE AGREE THAT ANY CLAIM BETWEEN US MUST BE BROUGHT WITHIN TWO (2) YEARS.<br>SOME JURISDICTIONS DO NOT ALLOW THE LIMITATION OR EXCLUSION OF LIABILITY FOR INCIDENTAL OF CONSEQUENTIAL DAMAGES, SO THE ABOVE LIMITATION OR EXCLUSION MAY NOT APPLY TO YOU AND YOU MAY ALSO HAVE OTHER LEGAL RIGHTS THAT VARY FROM JURISDICTION TO JURISDICTION.</strong></p>
		<p><strong>Indemnity</strong>
			<br>You agree to indemnify and hold&nbsp;<strong>PETSSIFIED.COM</strong>&nbsp;, our officers, employees, agents, affiliates, subsidiaries, parents, joint ventures, successors and any other companies under common control with us harmless, including costs and attorneys’ fees, from any claim or demand made by any third party due to or arising out of (i) your use of the Site or Products, (ii) your User Content, or (iii) your violation of this Agreement.&nbsp;<strong>PETSSIFIED.COM</strong>&nbsp;reserves the right, at your expense, to assume the exclusive defense and control of any matter for which you are required to indemnify us and you agree to cooperate with our defense of these claims. You agree not to settle any matter without the prior written consent of&nbsp;<strong>PETSSIFIED.COM</strong>.&nbsp;<strong>PETSSIFIED.COM</strong>&nbsp;will use reasonable efforts to notify you of any such claim, action or proceeding upon becoming aware of it.
			<br>
			<br><strong>Arbitration<br></strong>YOU AND&nbsp;<strong>PETSSIFIED.COM</strong>&nbsp;AGREE TO GIVE UP ANY RIGHTS TO LITIGATE CLAIMS IN A COURT OR BEFORE A JURY OR TO PARTICIPATE IN A CLASS ACTION OR REPRESENTATIVE ACTION WITH RESPECT TO A CLAIM. OTHER RIGHTS THAT YOU WOULD HAVE IF YOU WENT TO COURT, SUCH AS ACCESS TO DISCOVERY, ALSO MAY BE UNAVAILABLE OR LIMITED IN ARBITRATION.
			<br>
			<br>Any dispute between you and&nbsp;<strong>PETSSIFIED.COM</strong>&nbsp;, its agents, employees, officers, directors, principals, successors, assigns, subsidiaries or affiliates (collectively for purposes of this section, ‘<strong>PETSSIFIED.COM</strong>&nbsp;‘) arising from or relating to these Terms of Use and their interpretation or the breach, termination or validity thereof, the relationships which result from these Terms of Use, including disputes about the validity, scope or enforceability of this arbitration provision (collectively, “Covered Disputes”) will be settled by binding arbitration administered by the JAMS, Inc. under its rules applicable to consumer disputes, in effect on the date thereof. Information on JAMS and how to start arbitration can be found at www.jamsadr.com or by calling 800-352-5267. For purposes of this section, these Terms of Use and related transactions will be subject to and governed by the Federal Arbitration Act, 9 U.S.C. sec. 1-16 (FAA).</p>
		<p>Prior to initiating any arbitration, the initiating party will give the other party at least 60-days’ advanced written notice of its intent to file for arbitration.&nbsp;<strong>PETSSIFIED.COM</strong>&nbsp;will provide such notice by e-mail to your e-mail address on file with&nbsp;<strong>PETSSIFIED.COM</strong>&nbsp;and you must provide such notice by e-mail to: </p>
		<form>
			<h4>Fill this form:</h4>
			<input type="text" placeholder="Your Name" value="" required=""><br>
			<input type="email" placeholder="Your Email" required=""><br>
			<textarea placeholder="Your Message" required=""></textarea><br>
			<button class="btn" type="submit">Submit form</button>
		</form>
		<p>During such 60-day notice period, the parties will endeavor to settle amicably by mutual discussions any Covered Disputes. Failing such amicable settlement and expiration of the notice period, either party may initiate arbitration. The arbitrator will have the power to grant whatever individual relief would be available in court under law or in equity and any award of the arbitrator(s) will be final and binding on each of the parties and may be entered as a judgment in any court of competent jurisdiction.</p>
		<p><strong>PETSSIFIED.COM AND YOU AGREE THAT ANY COVERED DISPUTE HEREUNDER WILL BE SUBMITTED TO ARBITRATION ON AN INDIVIDUAL BASIS ONLY. NEITHER&nbsp;PETSSIFIED.COM&nbsp;NOR YOU ARE ENTITLED TO ARBITRATE ANY COVERED DISPUTE AS A CLASS, REPRESENTATIVE OR PRIVATE ATTORNEY ACTION AND THE ARBITRATOR(S) WILL HAVE NO AUTHORITY TO PROCEED ON A CLASS, REPRESENTATIVE OR PRIVATE ATTORNEY GENERAL BASIS.</strong>&nbsp;If any provision of the agreement to arbitrate in this section is found unenforceable, the unenforceable provision will be severed and the remaining arbitration terms will be enforced (but in no case will there be a class, representative or private attorney general arbitration).
			<br>Notwithstanding any provision in these terms to the contrary, we agree that if&nbsp;<strong>PETSSIFIED.COM</strong>&nbsp;makes any future material change to this dispute resolution provision, it will not apply to any individual claim(s) that you had already provided notice to&nbsp;<strong>PETSSIFIED.COM</strong>&nbsp;. In the event that this arbitration agreement does not apply to a given dispute, then the parties agree to the exclusive jurisdiction of the state and federal courts in Broward County, Florida to resolve such claims.</p>
		<p><strong>Term and Termination</strong>
			<br>Subject to this Section, this Agreement will remain in full force and effect while you use the Site. We may (a) suspend your rights to use the Site (as well as your&nbsp;<strong>PETSSIFIED.COM</strong>&nbsp;Account) or (b) terminate this Agreement, at any time for any reason at our sole discretion, including for any use of the Site in violation of this Agreement or if we believe you are younger than 18. Upon termination of this Agreement, your&nbsp;<strong>PETSSIFIED.COM</strong>&nbsp;Account and right to access and use the Site will terminate immediately. You understand that any termination of your&nbsp;<strong>PETSSIFIED.COM</strong>&nbsp;Account may involve deletion of any User Content you may have posted.&nbsp;<strong>PETSSIFIED.COM</strong>&nbsp;will not have any liability whatsoever to you for any termination of this Agreement, including for termination of your&nbsp;<strong>PETSSIFIED.COM</strong>&nbsp;Account or deletion of your User Content.</p>
		<p>The provisions herein related to our intellectual property rights, user content, acceptable use, disclaimer of warranties, indemnity, limitation and liability, and arbitration together with any other rights and obligations which by their nature are reasonably intended to survive such termination, will survive any termination of these Terms of Use.</p>
		<p><strong>Respect for Copyright Law</strong>
			<br><strong>PETSSIFIED.COM</strong>&nbsp;respects the intellectual property of others and asks that users of our Site do the same. Except as authorized above, you are not permitted access or use of any of&nbsp;<strong>PETSSIFIED.COM</strong>&nbsp;‘s Intellectual Property without our prior written consent or the consent of such third party that may own intellectual property with respect to Products displayed on the web site. In connection with our Site, Products, and any services we offer, we have adopted and reasonably implemented a policy respecting copyright law that provides for the removal of any infringing materials and for the termination, in appropriate circumstances, of users of our Site who are repeat infringers of intellectual property rights, including copyrights. If you believe that your work has been copied in a way that constitutes copyright infringement and wish to have the allegedly infringing material removed from our Site, the following information in the form of a written notification (pursuant to 17 U.S.C. Â§ 512(c)) must be provided to our designated Copyright Agent:</p>
		<ul>
			<li>your physical or electronic signature</li>            

			<li>identification of the copyrighted work(s) that you claim to have been infringed</li>
			<li>identification of the material on our services that you claim is infringing and that you request us to remove</li>
			<li>sufficient information to permit us to locate such material</li>
			<li>your address, telephone number, and e-mail address</li>
			<li>A statement that you have a good faith belief that use of the objectionable material is not authorized by the copyright owner, its agent, or under the law; and</li>
			<li>A statement that the information in the notification is accurate, and under penalty of perjury, that you are either the owner of the copyright that has allegedly been infringed or that you are authorized to act on behalf of the copyright owner</li>
		</ul>
		<p>Please note that, pursuant to 17 U.S.C. Â§ 512(f), any misrepresentation of material fact (falsities) in a written notification automatically subjects the complaining party to liability for any damages, costs and attorneys’ fees incurred by us in connection with the written notification and allegation of copyright infringement.
			<br>You may submit your counter notification to PETSSIFIED.COM ‘s Copyright Agent by mail or email as set forth below:
			<br>PETSSIFIED.COMt
			<br>Attn: Legal
			<br>3773 Howard Hughes Parkway Suite 500s, Las Vegas, NV 89169
			<br>Feel free to contact us:</p>
		<form>
			<h4>Fill this form:</h4>
			<input type="text" placeholder="Your Name" value="" required=""><br>
			<input type="email" placeholder="Your Email" required=""><br>
			<textarea placeholder="Your Message" required=""></textarea><br>
			<button class="btn" type="submit">Submit form</button>
		</form>
		<p><strong>General</strong>
			<br>We reserve the right to make changes to our Site, this Agreement and other service terms, such as our Privacy Policy and the Subscribe &amp; Save Terms &amp; Conditions at any time. Each time you use our Site, you should visit and review the then current Terms and Policies that apply to your transactions and use of our Site. If you do not agree to be bound by the then current Terms and Policies, your sole remedy is not to use our Site. If any terms of this Agreement or other service terms are deeded invalid, void, or for any reason unenforceable, any such term shall be deemed severable and shall not affect the validity and enforceability of any other terms.
			<br>This Agreement constitutes the entire agreement between you and us regarding the use of the Site and the purchase of any Products on our Site. Our failure to exercise or enforce any right or provision of this Agreement shall not operate as a waiver of such right or provision. This Agreement is governed by the laws of the State of Florida without regard to conflict of law provisions. The section titles in this Agreement are for convenience only and have no legal or contractual effect. The word “including” means including without limitation. If any provision of this Agreement is, for any reason, held to be invalid or unenforceable, the other provisions of this Agreement will be unimpaired and the invalid or unenforceable provision will be deemed modified so that it is valid and enforceable to the maximum extent permitted by law. This Agreement, and your rights and obligations herein, may not be assigned, subcontracted, delegated, or otherwise transferred by you without PETSSIFIED.COM ‘s prior written consent, and any attempted assignment, subcontract, delegation, or transfer in violation of the foregoing will be null and void. The terms of this Agreement shall be binding upon assignees.</p>
		<h4>Who we are</h4>
		<p>Our website address is: <a title="Petssified.com" href="https://petssified.com">https://petssified.com</a></p>
		<h2>What personal data we collect and why we collect it</h2>
		<h3>Comments</h3>
		<p>When visitors leave comments on the site we collect the data shown in the comments form, and also the visitor’s IP address and browser user agent string to help spam detection.</p>
		<p>An anonymized string created from your email address (also called a hash) may be provided to the Gravatar service to see if you are using it. The Gravatar service privacy policy is available here: https://automattic.com/privacy/. After approval of your comment, your profile picture is visible to the public in the context of your comment.</p>
		<h3>Media</h3>
		<p>If you upload images to the website, you should avoid uploading images with embedded location data (EXIF GPS) included. Visitors to the website can download and extract any location data from images on the website.</p>
		<h3>Contact forms</h3>
		<h3>Cookies</h3>
		<p>If you leave a comment on our site you may opt-in to saving your name, email address and website in cookies. These are for your convenience so that you do not have to fill in your details again when you leave another comment. These cookies will last for one year.</p>
		<p>If you visit our login page, we will set a temporary cookie to determine if your browser accepts cookies. This cookie contains no personal data and is discarded when you close your browser.</p>
		<p>When you log in, we will also set up several cookies to save your login information and your screen display choices. Login cookies last for two days, and screen options cookies last for a year. If you select “Remember Me”, your login will persist for two weeks. If you log out of your account, the login cookies will be removed.</p>
		<p>If you edit or publish an article, an additional cookie will be saved in your browser. This cookie includes no personal data and simply indicates the post ID of the article you just edited. It expires after 1 day.</p>
		<h3>Embedded content from other websites</h3>
		<p>Articles on this site may include embedded content (e.g. videos, images, articles, etc.). Embedded content from other websites behaves in the exact same way as if the visitor has visited the other website.</p>
		<p>These websites may collect data about you, use cookies, embed additional third-party tracking, and monitor your interaction with that embedded content, including tracking your interaction with the embedded content if you have an account and are logged in to that website.</p>
		<h3>Analytics</h3>
		<h2>Who we share your data with</h2>
		<h2>How long we retain your data</h2>
		<p>If you leave a comment, the comment and its metadata are retained indefinitely. This is so we can recognize and approve any follow-up comments automatically instead of holding them in a moderation queue.</p>
		<p>For users that register on our website (if any), we also store the personal information they provide in their user profile. All users can see, edit, or delete their personal information at any time (except they cannot change their username). Website administrators can also see and edit that information.</p>
		<h2>What rights you have over your data</h2>
		<p>If you have an account on this site, or have left comments, you can request to receive an exported file of the personal data we hold about you, including any data you have provided to us. You can also request that we erase any personal data we hold about you. This does not include any data we are obliged to keep for administrative, legal, or security purposes.</p>
		<h2>Where we send your data</h2>
		<p>Visitor comments may be checked through an automated spam detection service.</p>
		<h2>Your contact information</h2>
		<h2>Additional information</h2>
		<p>How we protect your data</p>
		<p>What data breach procedures we have in place</p>
		<p>What third parties we receive data from</p>
		<p>What automated decision making and/or profiling we do with user data</p>
		<p>Industry regulatory disclosure requirements</p>
</div>