<?php

return [
    'jquery' => 'vendor/jquery/dist/jquery.min.js',
    'jqueryui' => 'vendor/jquery-ui/jquery-ui.min.js',
    'bootstrap' => 'vendor/bootstrap/dist/js/bootstrap.min.js',
    'raphael' => 'vendor/raphael/raphael.min.js',
    'morris' => 'vendor/morris.js/morris.min.js',
    'sparkline' => 'vendor/jquery-sparkline/dist/jquery.sparkline.min.js',
    'knob' => 'vendor/jquery-knob/dist/jquery.knob.min.js',
    'moment' => 'vendor/moment/min/moment.min.js',
    'daterangepicker' => 'vendor/bootstrap-daterangepicker/daterangepicker.js',
    'datepicker' => 'vendor/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js',
    'chartJs' => 'vendor/chartjs/Chart.js',
    'slimscroll' => 'vendor/jquery-slimscroll/jquery.slimscroll.min.js',
    'fastclick' => 'vendor/fastclick/lib/fastclick.js',
    'adminlte' => 'js/adminlte.min.js',
    'select2' => 'vendor/select2/dist/js/select2.min.js',
    'dashboard' => 'js/dashboard.js',
    'phillips_api' => 'js/phillips_api.js',
    'leemarpet_sheet' => 'js/leemarpet_sheet.js',
    'lodash' => 'js/lodash.js',
    'add_product' => 'js/add_product.js',
    'edit_product' => 'js/edit_product.js',
    'upload_product_image' => 'js/upload_product_image.js',
    'admin_all_users' => 'js/admin_all_users.js',
    'single_category' => 'js/single_category.js',
];
