<div class="content-area">

    <h1>ANTI DISCRIMINATORY POLICY</h1>	
    <hr>

    <h4>Objective</h4>
    <p>Petssified.com, Inc.  is committed to a work environment in which all individuals are treated with respect and dignity. Each individual has the right to work in a professional atmosphere that promotes equal employment opportunities and prohibits unlawful discriminatory practices, including harassment. Therefore, Petssified.com, Inc.  expects that all relationships among persons in the office will be business-like and free of explicit bias, prejudice and harassment.
    </p><p>Petssified.com, Inc.  has developed this policy to ensure that all its employees can work in an environment free from unlawful harassment, discrimination and retaliation. Petssified.com, Inc.  will make every reasonable effort to ensure that all concerned are familiar with these policies and are aware that any complaint in violation of such policies will be investigated and resolved appropriately.
    </p><p>Any employee who has questions or concerns about these policies should talk with the director of human resources or a member of the personnel practices committee.
    </p><p>These policies should not, and may not, be used as a basis for excluding or separating individuals of a particular gender, or any other protected characteristic, from participating in business or work-related social activities or discussions. In other words, no one should make the mistake of engaging in discrimination or exclusion to avoid allegations of harassment. The law and the policies of Petssified.com, Inc.  prohibit disparate treatment on the basis of sex or any other protected characteristic, with regard to terms, conditions, privileges and perquisites of employment. The prohibitions against harassment, discrimination and retaliation are intended to complement and further those policies, not to form the basis of an exception to them.

    </p><h4>Equal employment opportunity</h4>
    <p>It is the policy of Petssified.com, Inc.  to ensure equal employment opportunity without discrimination or harassment on the basis of race, color, religion, sex, sexual orientation, gender identity or expression, age, disability, marital status, citizenship, national origin, genetic information, or any other characteristic protected by law. Petssified.com, Inc.  prohibits any such discrimination or harassment.


    </p><h4>Retaliation</h4>
    <p>Petssified.com, Inc.  encourages reporting of all perceived incidents of discrimination or harassment. It is the policy of Petssified.com, Inc.  to promptly and thoroughly investigate such reports. Petssified.com, Inc.  prohibits retaliation against any individual who reports discrimination or harassment or participates in an investigation of such reports.

    </p><h4>Sexual harassment</h4>
    <p>Sexual harassment constitutes discrimination and is illegal under federal, state and local laws. For the purposes of this policy, “sexual harassment” is defined, as in the Equal Employment Opportunity Commission Guidelines, as unwelcome sexual advances, requests for sexual favors and other verbal or physical conduct of a sexual nature when, for example: a) submission to such conduct is made either explicitly or implicitly a term or condition of an individual’s employment, b) submission to or rejection of such conduct by an individual is used as the basis for employment decisions affecting such individual, or c) such conduct has the purpose or effect of unreasonably interfering with an individual’s work performance or creating an intimidating, hostile or offensive working environment.
    </p><p>Title VII of the Civil Rights Act of 1964 recognizes two types of sexual harassment: a) quid pro quo and b) hostile work environment. Sexual harassment may include a range of subtle and not-so-subtle behaviors and may involve individuals of the same or different gender. Depending on the circumstances, these behaviors may include unwanted sexual advances or requests for sexual favors; sexual jokes and innuendo; verbal abuse of a sexual nature; commentary about an individual’s body, sexual prowess or sexual deficiencies; leering, whistling or touching; insulting or obscene comments or gestures; display in the workplace of sexually suggestive objects or pictures; and other physical, verbal or visual conduct of a sexual nature.

    </p><h4>Harassment</h4>
    <p>Harassment on the basis of any other protected characteristic is also strictly prohibited. Under this policy, harassment is verbal, written or physical conduct that denigrates or shows hostility or aversion toward an individual because of his or her race, color, religion, sex, sexual orientation, gender identity or expression, national origin, age, disability, marital status, citizenship, genetic information, or any other characteristic protected by law, or that of his or her relatives, friends or associates, and that: a) has the purpose or effect of creating an intimidating, hostile or offensive work environment, b) has the purpose or effect of unreasonably interfering with an individual’s work performance, or c) otherwise adversely affects an individual’s employment opportunities.
    </p><p>Harassing conduct includes epithets, slurs or negative stereotyping; threatening, intimidating or hostile acts; denigrating jokes; and written or graphic material that denigrates or shows hostility or aversion toward an individual or group that is placed on walls or elsewhere on the employer’s premises or circulated in the workplace, on company time or using company equipment by e-mail, phone (including voice messages), text messages, social networking sites or other means.

    </p><h4>Individuals and Conduct Covered</h4>
    <p>These policies apply to all applicants and employees, whether related to conduct engaged in by fellow employees or by someone not directly connected to Petssified.com, Inc.  (e.g., an outside vendor, consultant or customer).
    </p><p>Conduct prohibited by these policies is unacceptable in the workplace and in any work-related setting outside the workplace, such as during business trips, business meetings and business-related social events.

    </p><h4>Reporting an Incident of Harassment, Discrimination or Retaliation</h4>
    <p>Petssified.com, Inc.  encourages reporting of all perceived incidents of discrimination, harassment or retaliation, regardless of the offender’s identity or position. Individuals who believe that they have been the victim of such conduct should discuss their concerns with their immediate supervisor, any member of the personnel practices committee, human resources or any ombudsman. See the complaint procedure described below.
    </p><p>In addition, Petssified.com, Inc.  encourages individuals who believe they are being subjected to such conduct to promptly advise the offender that his or her behavior is unwelcome and to request that it be discontinued. Often this action alone will resolve the problem. Petssified.com, Inc.  recognizes, however, that an individual may prefer to pursue the matter through complaint procedures.

    </p><h4>Complaint Procedure</h4>
    <p>Individuals who believe they have been the victims of conduct prohibited by this policy or believe they have witnessed such conduct should discuss their concerns with their immediate supervisor, human resources, any member of the personnel practices committee or any ombudsman.
    </p><p>Petssified.com, Inc.  encourages the prompt reporting of complaints or concerns so that rapid and constructive action can be taken before relationships become irreparably strained. Therefore, while no fixed reporting period has been established, early reporting and intervention have proven to be the most effective method of resolving actual or perceived incidents of harassment.
    </p><p>Any reported allegations of harassment, discrimination or retaliation will be investigated promptly. The investigation may include individual interviews with the parties involved and, where necessary, with individuals who may have observed the alleged conduct or may have other relevant knowledge.
    </p><p>Petssified.com, Inc.  will maintain confidentiality throughout the investigatory process to the extent consistent with adequate investigation and appropriate corrective action.
    </p><p>Retaliation against an individual for reporting harassment or discrimination or for participating in an investigation of a claim of harassment or discrimination is a serious violation of this policy and, like harassment or discrimination itself, will be subject to disciplinary action. Acts of retaliation should be reported immediately and will be promptly investigated and addressed.
    </p><p>Misconduct constituting harassment, discrimination or retaliation will be dealt with appropriately. Responsive action may include, for example, training, referral to counseling or disciplinary action such as a warning, reprimand, withholding of a promotion or pay increase, reassignment, temporary suspension without pay, or termination, as Petssified.com, Inc.  believes appropriate under the circumstances.
    </p><p>If a party to a complaint does not agree with its resolution, that party may appeal to Petssified.com, Inc. executive director or the chief operating officer.
    </p><p>False and malicious complaints of harassment, discrimination or retaliation (as opposed to complaints that, even if erroneous, are made in good faith) may be the subject of appropriate disciplinary action.


    </p>
</div>
